### COMMON VARIABLES
@protocol = http
@host = localhost
@port = 3000
@base_url = {{protocol}}://{{host}}:{{port}}
@content_type = application/json

@basic_auth = Basic YWxhZGRpbjpvcGVuc2VzYW1l
@bearer_auth = Bearer xxx
@auth = {{basic_auth}} user:passwd

### CHECK URL END WITH SLASH (root or /)
POST {{base_url}}/
content-type: {{content_type}}
authorization: {{auth}}

{

}

### CHECK URL END WITH SLASH (/users/)
GET {{base_url}}/users/
content-type: {{content_type}}

{

}

### CHECK URL END WITH NO SLASH (root)
GET {{base_url}}
content-type: {{content_type}}

{

}

### CHECK URL END WITH NO SLASH (/users)
GET {{base_url}}/users
content-type: {{content_type}}

{

}

### TEST RESPONSE TIMEOUT
POST {{base_url}}/execute
content-type: {{content_type}}

{
    "timeout": 10000
}

### TEST CHECK TIMEOUT
POST {{base_url}}/check
content-type: {{content_type}}

{
    "timeout": 1000
}
